In [2]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
arreglo=np.zeros(10)
arreglo[5]=1
print(arreglo)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [17]:
arreglo4=np.arange(50)
arreglo4_1=arreglo4[::-1]
print(arreglo4)
print(arreglo4_1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [34]:
arreglo5=np.arange(9)
arreglo5_1=arreglo5.reshape(3,3)
print(arreglo5_1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [37]:
arreglo6 = [1, 2, 0, 0, 4, 0]
arreglo6_1 = (arreglo6 != 0)
arreglo6[arreglo6_1]
print (arreglo6_1)

True


In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.random.random((3,3,3))

array([[[0.29837583, 0.21408908, 0.29569059],
        [0.56980104, 0.29570348, 0.98279616],
        [0.78893799, 0.53168812, 0.57381572]],

       [[0.9889822 , 0.95513882, 0.19238923],
        [0.08363461, 0.34092134, 0.49586933],
        [0.95687429, 0.20673244, 0.63280175]],

       [[0.30213907, 0.89431147, 0.55790704],
        [0.3433638 , 0.74643532, 0.54759207],
        [0.40835713, 0.38634294, 0.84201952]]])

In [57]:
arreglo9 = np.arange(100)
matriz9 = arreglo9.reshape(10,10)
print(matriz9.max())
print(matriz9.min())

99
0


In [58]:
import numpy as np
from scipy import ndimage
from scipy import misc
mapache = misc.face()
mapache

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [60]:
#11
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
pd.Series(mylist)
pd.Series(myarr)
pd.Series(mydict)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [62]:
#12) ¿Como convertir el indice de una serie en una columna de un DataFrame?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 

dataf12 = pd.DataFrame(
    ser,
    columns = [
    'Columna1',
    'Columna2'],
    index = [
        'indice'])

ValueError: Shape of passed values is (1, 1), indices imply (1, 2)

In [ ]:
#13) ¿Como combinar varias series para hacer un DataFrame?
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df13 = pd.DataFrame(ser1, columns = ['letras'])
df13_1 = pd.DataFrame(ser2, columns = ['numeros'])
df13 = pd.concat([df3, df13_1])

In [ ]:
#14) ¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
serie14 = pd.Series(ser1) && pd.Series(ser2)

In [ ]:
#20) ¿Como anadir series vertical u horizontalmente a un DataFrame?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

df20 = pd.DataFrame(ser1, columns = ['ser1', 'ser2'], index = ['in1', 'in2'])
df20_1 = df20 ['ser1']
df20_2 = df20 ['in1']
print(df20_1)
print (df20_2)

In [69]:
#21)¿Obtener la media de una serie agrupada por otra serie?
#groupby tambien esta disponible en series.

frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64

ser21 = pd.Series(np.average(pesos))
print (ser21)

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'manzana', 'manzana', 'zanahoria', 'banana', 'zanahoria', 'zanahoria', 'manzana', 'zanahoria', 'zanahoria']
0    5.5
dtype: float64


In [66]:
#22)¿Como importar solo columnas especificas de un archivo csv? ,
#    index_col = 'id'
import pandas as pd
import os

path = "./BostonHousing.csv"
columnas = ["age"]
df22 = pd.read_csv(path, nrows=10, usecols = columnas)
print (df22)

     age
0   65.2
1   78.9
2   61.1
3   45.8
4   54.2
5   58.7
6   66.6
7   96.1
8  100.0
9   85.9
