In [2]:
# pip install numpy
# conda install numpy
import numpy as np

In [8]:
print(type([1,2,3]))
print(type((1,2,3))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3)))

SyntaxError: unexpected EOF while parsing (<ipython-input-8-c04f42a15709>, line 2)

In [16]:
np.zeros(5)  # 1 solo numero para un arreglo
np.zeros([5,5]) # 1 lista o una tupla para una matriz de n dimensiones
np.zeros((5,5))
np.zeros((2,3,4))
np.zeros([2,3,4,1,2,1])
np.zeros([1000,200])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
np.ones(7)
np.ones((1,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [19]:
np.eye(5) #Matriz identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.arange(5) # 1 parametro, # de elementos

array([0, 1, 2, 3, 4])

In [22]:
np.arange(4,20) # [4,20[

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(-12,1) # [-12,1[

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [25]:
np.arange(0,20,2) # [0,20[ en intervalos de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.arange(0,2,0.1) # [0,2[ en intervalos de 0.1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [32]:
np.arange(10) #1 dimension con 10 elementos
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
np.zeros(20).reshape(2,5,2).reshape(2,10) #para hacer redimensiones 
#tenemos que saber cuantos elementos tenemos

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
len(np.ones(12))

12

In [36]:
len(np.ones(12).reshape(4,3)) #len la longitud del arreglo

4

In [37]:
np.ones(12).reshape(4,3).shape

(4, 3)

In [38]:
np.arange(12).reshape(4,3)[1,2]

5

In [40]:
np.array([1,7,12,16]).reshape(2,2)

array([[ 1,  7],
       [12, 16]])

In [41]:
a=np.array([10,10,10])
b=np.array([5,5,5])

In [42]:
#suma
a + b

array([15, 15, 15])

In [43]:
#resta
a - b

array([5, 5, 5])

In [44]:
#suma
a + 7

array([17, 17, 17])

In [45]:
#resta
a - 8

array([2, 2, 2])

In [46]:
#multiplicacion
a * b

array([50, 50, 50])

In [47]:
#multiplicacion
a * 3

array([30, 30, 30])

In [48]:
# division
a / b

array([2., 2., 2.])

In [49]:
# division
a / 2

array([5., 5., 5.])

In [50]:
# Modulo
a % b

array([0, 0, 0], dtype=int32)

In [51]:
# Modulo
a % 3

array([1, 1, 1], dtype=int32)

In [52]:
muestra = np.arange(20).reshape(5,2,2)

In [53]:
muestra

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [54]:
respuesta_glucosa = muestra > 5 

In [55]:
respuesta_glucosa

array([[[False, False],
        [False, False]],

       [[False, False],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [57]:
muestra [respuesta_glucosa]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [105]:
#Mayores a 5 glucosa y menores a 14 y que sean pares
mayores_cinco = muestra>5
menores_catorce = muestra<14
pares = muestra % 2 == 0
respuesta = mayores_cinco & menores_catorce & pares

In [107]:
muestra [respuesta]

array([ 6,  8, 10, 12])

In [121]:
respuesta = (muestra > 5) & (muestra<14) & (muestra % 2 == 0)

In [122]:
muestra[respuesta]

array([ 6,  8, 10, 12])

In [124]:
muestra[(muestra > 5) & (muestra<14) & (muestra % 2 == 0)]

array([ 6,  8, 10, 12])

In [4]:
A = np.arange(4).reshape (2,2)
A

array([[0, 1],
       [2, 3]])

In [7]:
B = np.arange(4,8).reshape (2,2)
B

array([[4, 5],
       [6, 7]])

In [8]:
A.dot(B)

array([[46, 55],
       [66, 79]])

In [9]:
B.dot(A)

array([[46, 55],
       [66, 79]])

In [10]:
np.dot(A,B)

array([[46, 55],
       [66, 79]])

In [12]:
np.dot(B,A)

array([[46, 55],
       [66, 79]])

In [13]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
arreglo_doce.sum()

66

In [15]:
arreglo_doce.min()

0

In [16]:
arreglo_doce.max()

11

In [17]:
arreglo_doce[5:].sum()

56

In [18]:
arreglo_doce.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [20]:
arreglo_doce.sum()

66

In [21]:
arreglo_doce.sum(axis=0)

66

In [22]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [23]:
arreglo_doce.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [24]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

AxisError: axis 3 is out of bounds for array of dimension 3