In [3]:
import numpy as np

In [6]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [7]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [8]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [9]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [10]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [12]:
numero_random = np.random.randint(
    11   # [0, 11[
)
numero_random

6

In [14]:
numero_random_negativo = np.random.randint(
    -9, 2  #[-9, 2[
)
numero_random_negativo

-4

In [15]:
arreglo_random = np.random.randint (
    10, 20, 8
)
arreglo_random

array([18, 10, 18, 10, 16, 16, 18, 15])

In [16]:
np.random.rand(9)  # 9 elementos
np.random.rand(3,2)  # 6 elementos (3 x 2 dimensiones)

array([[0.38354872, 0.13635518],
       [0.10701341, 0.33677454],
       [0.38932696, 0.40393798]])

In [20]:
np.average(arreglo_random)

15.125

In [21]:
np.mean(arreglo_random)

15.125

In [22]:
np.median(arreglo_random)

16.0

In [23]:
np.std(arreglo_random)

3.1399641717701177

In [25]:
np.var(arreglo_random)

9.859375

In [26]:
arreglo_random.mean()

15.125