#  Examen Santiago Collaguazo

## 1) Crea un Dataframe de 10 registros y 6 columnas y consigue las 5 primeros y los 5 ultimos registros



In [6]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame(np.random.randint(0,10,60).reshape(10,6))
print('Primeros 5 registros')
print(df1.head(5))
print('Ultimos 5 registros')
print(df1.tail(5))


Primeros 5 registros
   0  1  2  3  4  5
0  6  5  8  5  0  0
1  3  2  4  5  0  9
2  2  3  6  6  8  4
3  9  7  5  5  6  9
4  0  9  3  2  1  2
Ultimos 5 registros
   0  1  2  3  4  5
5  8  4  3  0  0  8
6  0  5  8  7  2  8
7  2  5  5  7  3  8
8  2  4  8  7  0  5
9  9  6  1  0  4  9


## 2) Crear un dataframe pasando un arreglo de numpy de 6 x 4 con una fecha como indice y con columnas A, B, C, D randomico

```
                   A         B         C         D
2013-01-01  0.469112 -0.282863 -1.509059 -1.135632
2013-01-02  1.212112 -0.173215  0.119209 -1.044236
2013-01-03 -0.861849 -2.104569 -0.494929  1.071804
2013-01-04  0.721555 -0.706771 -1.039575  0.271860
2013-01-05 -0.424972  0.567020  0.276232 -1.087401
2013-01-06 -0.673690  0.113648 -1.478427  0.524988
```

In [12]:
from datetime import date
v2 = np.random.randint(0,5,24).reshape(6, 4)
c = ['A', 'B', 'C', 'D']
i = [date.today(),
           date.today(),
           date.today(),
           date.today(),
           date.today(),
           date.today()]
df2 = pd.DataFrame(v2, columns = c, index = i)
print(df2)

            A  B  C  D
2020-10-05  1  0  0  1
2020-10-05  3  3  4  2
2020-10-05  1  4  1  3
2020-10-05  2  4  1  2
2020-10-05  2  4  1  3
2020-10-05  2  1  3  1


## 4) Crear un Dataframe con 10 registros y 6 columnas y con una propiedad del Dataframe mostrar las columnas, con otro comando mostrar los valores.

In [17]:
df4 = pd.DataFrame(np.random.randint(0,10,60).reshape(10, 6))
print("Columnas\n ", df4.columns.tolist())
print("Valores\n", df4.values)

Columnas
  [0, 1, 2, 3, 4, 5]
Valores
 [[2 5 9 9 4 1]
 [0 6 6 2 6 0]
 [1 3 3 5 2 9]
 [0 6 7 3 4 5]
 [2 1 6 6 4 1]
 [5 9 1 0 7 7]
 [1 8 1 7 5 0]
 [0 0 6 4 8 3]
 [1 4 4 4 8 9]
 [0 9 3 3 8 9]]
